"""
DISCLAIMER INJECTOR — adds legal disclaimer to ALL outputs before they leave the system.
BOUNDARY: injects disclaimer only. Never modifies content.
"""
from ..base import BaseAgent

DISCLAIMER_EN = (
    "DISCLAIMER: This information is generated by an automated system for guidance purposes only. "
    "It does NOT constitute legal, tax, or financial advice. Tax laws change frequently. "
    "Always verify with the Kenya Revenue Authority (KRA) or a registered tax advisor "
    "before making any filing or payment decisions. KRA Deadline Tracker is not liable for any "
    "penalties, losses, or decisions made based on this information."
)

DISCLAIMER_SW = (
    "ONYO: Taarifa hii imetolewa na mfumo wa kiotomatiki kwa madhumuni ya kuongoza tu. "
    "Hii SI ushauri wa kisheria, kodi, au kifedha. Sheria za kodi hubadilika mara kwa mara. "
    "Daima hakikisha na Mamlaka ya Mapato Kenya (KRA) au mshauri wa kodi aliyesajiliwa "
    "kabla ya kufanya uamuzi wowote wa kuwasilisha au kulipa. KRA Deadline Tracker haihusiki na "
    "adhabu, hasara, au maamuzi yaliyofanywa kulingana na taarifa hii."
)


class DisclaimerInjector(BaseAgent):
    name = "disclaimer_injector"
    boundary = "Injects disclaimer only. Never modifies content."

    def inject(self, output: dict, language: str = "en") -> dict:
        """Add disclaimer to any output dict."""
        disclaimer = DISCLAIMER_SW if language == "sw" else DISCLAIMER_EN
        output["disclaimer"] = disclaimer
        return output

    def get_disclaimer(self, language: str = "en") -> str:
        return DISCLAIMER_SW if language == "sw" else DISCLAIMER_EN
